// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVu-ZHc15u2eLIboyjR6RDfgDvvL2NBO4',
    appId: '1:72886769722:web:146a3ee09abccd0910fd03',
    messagingSenderId: '72886769722',
    projectId: 'kado-b99cd',
    authDomain: 'kado-b99cd.firebaseapp.com',
    storageBucket: 'kado-b99cd.appspot.com',
    measurementId: 'G-VBY4WZWVZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1GGMQOjCkM8oHhP3Ii65-Yx0GELnud6M',
    appId: '1:72886769722:android:f3d68644fba1ce7010fd03',
    messagingSenderId: '72886769722',
    projectId: 'kado-b99cd',
    storageBucket: 'kado-b99cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxNmZigEhedt_1m-IZYxK8_XRwHVYNn60',
    appId: '1:72886769722:ios:90a89daa695cf7c210fd03',
    messagingSenderId: '72886769722',
    projectId: 'kado-b99cd',
    storageBucket: 'kado-b99cd.appspot.com',
    iosClientId: '72886769722-g63pitig54f8001e7tq87gudqrth0qq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.kado',
  );
}
